[workspace]
release = false
publish = false
dependencies_update = true
git_release_enable = true
git_tag_name = "v{{ version }}"
git_release_name = "v{{ version }}"

[[package]]
name = "jigs-core"
release = true
publish = true

[[package]]
name = "jigs-macros"
release = true
publish = true

[[package]]
name = "jigs-trace"
release = true
publish = true

[[package]]
name = "jigs"
release = true
publish = true
